<a href="https://colab.research.google.com/github/Vyshnavi262007/Advanced-Python-Programming/blob/main/APP10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
traffic_data = [
    [120, 150, 180],
    [200, 220, 250],
    [80, 100, 90],
    [160, 190, 210]
]

In [3]:
traffic_array = np.array(traffic_data)

print("Traffic Data:")
print(traffic_array)

Traffic Data:
[[120 150 180]
 [200 220 250]
 [ 80 100  90]
 [160 190 210]]


In [4]:
traffic_array = traffic_array.reshape(4, 3)

print("Reshaped Traffic Data:")
print(traffic_array)

Reshaped Traffic Data:
[[120 150 180]
 [200 220 250]
 [ 80 100  90]
 [160 190 210]]


In [5]:
total_traffic = np.sum(traffic_array)

print("Total Traffic:", total_traffic)

Total Traffic: 1950


In [6]:
average_traffic = np.mean(traffic_array)

print("Average Traffic:", average_traffic)

Average Traffic: 162.5


In [7]:
traffic_std = np.std(traffic_array)

print("Standard Deviation:", traffic_std)

Standard Deviation: 52.93470821052416


In [8]:
location_total = np.sum(traffic_array, axis=1)
location_average = np.mean(traffic_array, axis=1)

print("Total traffic at each location:")
print(location_total)

print("\nAverage traffic at each location:")
print(location_average)

Total traffic at each location:
[450 670 270 560]

Average traffic at each location:
[150.         223.33333333  90.         186.66666667]


In [9]:
high_traffic = location_average >= 180

print("High-Traffic Locations:")
print(high_traffic)

High-Traffic Locations:
[False  True False  True]


In [10]:
most_congested = np.argmax(location_average)

print("Most Congested Location: Location", most_congested + 1)
print("Average Traffic:", location_average[most_congested])

Most Congested Location: Location 2
Average Traffic: 223.33333333333334


In [11]:
time_average = np.mean(traffic_array, axis=0)

print("Average Traffic for Each Time Slot:")
print(time_average)

Average Traffic for Each Time Slot:
[140.  165.  182.5]


In [13]:
# Define categories based on the high_traffic boolean array
categories = ["High Traffic" if is_high else "Normal Traffic" for is_high in high_traffic]

print("----- SMART TRAFFIC DATA SUMMARY -----")

print("Total Traffic:", total_traffic)
print("Overall Average Traffic:", average_traffic)
print("Standard Deviation:", traffic_std)

for i in range(4):
    print(
        "Location", i + 1,
        "- Total:", location_total[i],
        "- Average:", location_average[i],
        "- Category:", categories[i]
    )

print("Most Congested Location:", most_congested + 1)

----- SMART TRAFFIC DATA SUMMARY -----
Total Traffic: 1950
Overall Average Traffic: 162.5
Standard Deviation: 52.93470821052416
Location 1 - Total: 450 - Average: 150.0 - Category: Normal Traffic
Location 2 - Total: 670 - Average: 223.33333333333334 - Category: High Traffic
Location 3 - Total: 270 - Average: 90.0 - Category: Normal Traffic
Location 4 - Total: 560 - Average: 186.66666666666666 - Category: High Traffic
Most Congested Location: 2
