<a href="https://colab.research.google.com/github/Vyshnavi262007/Advanced-Python-Programming/blob/main/APP10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np

In [41]:
locations = ["Main Road", "City Center", "Residential Area", "Highway Junction"]
time_slots = ["Morning", "Afternoon", "Evening"]

print("Locations:", locations)
print("Time Slots:", time_slots)
print("Time Slots:", time_slots)

Locations: ['Main Road', 'City Center', 'Residential Area', 'Highway Junction']
Time Slots: ['Morning', 'Afternoon', 'Evening']


In [42]:
traffic_data = [
    [120, 150, 180],
    [200, 220, 250],
    [80, 100, 90],
    [160, 190, 210]
]

In [43]:
traffic_array = np.array(traffic_data)

print("Traffic Data:")
print(traffic_array)

Traffic Data:
[[120 150 180]
 [200 220 250]
 [ 80 100  90]
 [160 190 210]]


In [44]:
traffic_array = traffic_array.reshape(4, 3)

print("Reshaped Traffic Data:")
print(traffic_array)

Reshaped Traffic Data:
[[120 150 180]
 [200 220 250]
 [ 80 100  90]
 [160 190 210]]


In [45]:
total_traffic = np.sum(traffic_array)

print("Total Traffic:", total_traffic)

Total Traffic: 1950


In [46]:
global_threshold = np.mean(traffic_array)

print("Global Traffic Threshold:", global_threshold)

Global Traffic Threshold: 162.5


In [47]:
traffic_std = np.std(traffic_array)

print("Standard Deviation:", traffic_std)

Standard Deviation: 52.93470821052416


In [48]:
total_traffic = np.sum(traffic_array, axis=1)
avg_traffic = np.mean(traffic_array, axis=1)
variation = np.std(traffic_array, axis=1)

In [49]:
print("\n========== SMART TRAFFIC SUMMARY ==========")

print("Global Traffic Threshold:", global_threshold)

print("\nLocation\t\tTotal Traffic\tAvg/Hour\tVariation (Std)")

for i in range(len(locations)):
    print(f"{locations[i]:20}\t{total_traffic[i]:12}\t{avg_traffic[i]:8.2f}\t{variation[i]:8.2f}")


========== SMART TRAFFIC SUMMARY ==========
Global Traffic Threshold: 162.5

Location		Total Traffic	Avg/Hour	Variation (Std)
Main Road           	         450	  150.00	   24.49
City Center         	         670	  223.33	   20.55
Residential Area    	         270	   90.00	    8.16
Highway Junction    	         560	  186.67	   20.55


In [50]:
print("\n========== TRAFFIC ALERT ==========")

high_traffic = avg_traffic > global_threshold

for i in range(len(locations)):
    if high_traffic[i]:
        print("ALERT: High traffic detected at", locations[i])


========== TRAFFIC ALERT ==========
ALERT: High traffic detected at City Center
ALERT: High traffic detected at Highway Junction
